### ISSUE TITLE
FEAT: Create Default offline page for DOWN services. 

### ISSUE THREAD

**Issue by seanvree** [seanvree/Monitorr#16]
The OFFLINE image already denotes that's it's down, but it will still be a hyperlink to the DOWN link, so we just need to point that link somewhere, either BACK to the index.php, or I would say let's create a quick offline page that the user can change via the settings.php page

**Comment by wjbeckett** [comment]
Can we maybe just send the offline to #? Don't think we really want to redirect users away from the page if they aren't using an uptime link. So maybe if the link is down by default we make it go to #.

**Comment by wjbeckett** [comment]
I have enabled the dynamic links. Currently the offline status redirects to #.
We can for sure add the option of a down link (to uptime robot for example) but that'll be another variable and I believe we should wait for the settings page for that otherwise config.php will get very messy very quickly.
